### ISSUE TITLE
use of create-meetup-2 folder

### ISSUE THREAD

**Issue by venkat2509** [CEN5035/gator-meetup#26]
Hi Siddhartha, When I pulled the code from master I noticed that instead of folder name Settings something like create-meetup-2 was used. Is there any specific reason for this? Please do let us all know

**Comment by siddharthakonakanchi** [comment]
Ya I will rename it

**Comment by divya0923** [comment]
@siddharthakonakanchi please do not change the folder structure. it is scaffolded by angular and making changes to directory structure might create problems
